### ISSUE TITLE
Remove a label when approved

### ISSUE THREAD

**Issue by axelson** [pullreminders/label-when-approved-action#1]
Would it be possible to optionally remove a label when a PR is approved?

**Comment by abinoda** [comment]
@axelson Should be easy to do. Would need to modify this line:
https://github.com/pullreminders/label-when-approved-action/blob/master/entrypoint.sh#L47-L53

You could fork and change your own or submit a PR here if you make it configurable.

**Comment by rciovati** [comment]
Should be done in #3
