### ISSUE TITLE
Action fails on existing PRs that don't define variable ADD_LABEL

### ISSUE THREAD

**Issue by Nikschavan** [pullreminders/label-when-approved-action#7]
Error message - `/entrypoint.sh: line 47: ADD_LABEL: unbound variable`
Example log of an action [here](https://github.com/brainstormforce/astra/pull/1449/checks?check_run_id=226409114#step:4:10)

This is related to #3

**Comment by abinoda** [comment]
@rciovati could you investigate?

**Comment by rciovati** [comment]
@abinoda sure, it's definitely something I broke 😅 
I'm not a bash guru but from my understanding changing the flags at the beginning of the script should work:

```
set -eu
```

to be only:

```
set -e
```

I cannot send a PR right now, I can probably do that tomorrow.
